services:
  transmission-rss:
    image: ghcr.io/ivanjx/transmission-rss-cs:latest
    container_name: transmission-rss
    restart: unless-stopped
    ports:
      - "8354:8354"
    volumes:
      - transmission-rss-data:/data

volumes:
  transmission-rss-data:
